name: prettier-config
org: fantacovid-19
install: true
packagePath: packages/prettier-config
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: fantacovid-19/utilities
gitHostVariant: github
